#!/bin/sh

alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias tmux="tmux attach || tmux -2" #Fix color for tmux

alias myvimup='vim +PluginInstall +qall'

alias mydot="cd ~/.dotfiles"
alias myalias="vim ~/.dotfiles/aliases"
alias myenv="vim ~/.dotfiles/zshenv"
alias myssh="vim ~/.ssh/config"

alias mysrc="cd $MY_SRC"
alias myrepo="cd $MY_REPO"
alias myproj="cd $MY_PROJ"
alias mybox="cd $MY_BOX"
alias mygo="cd $MY_GO"
alias myopt="cd $MY_OPT"
alias mygocur="export GOPATH=`pwd`:$GOPATH"

alias setmyproxy="export HTTP_PROXY=\"http://127.0.0.1:1082\" HTTPS_PROXY=\"http://127.0.0.1:1082\""
alias unsetmyproxy="export HTTP_PROXY=\"\" && export HTTPS_PROXY=\"\""

alias mpw="cd $MY_PWORK"
alias mpr="cd $MY_PREPO"
