#!/bin/sh
if [ `uname` = "Linux" ]; then
    alias ls="ls --color=auto"
fi
alias grep="grep --color=auto"
alias tmux="tmux attach || tmux -2" #Fix color for tmux

alias myvimup='vim +PluginInstall +qall'

alias mydot="cd ~/.dotfiles"
alias myalias="vim ~/.dotfiles/aliases"
alias myenv="vim ~/.dotfiles/zshenv"
alias myssh="vim ~/.ssh/config"

alias mysrc="cd $MY_WS_SRC"
alias myrepo="cd $MY_WS_REPO"
alias myproj="cd $MY_WS_PROJ"
alias mybox="cd $MY_WS_BOX"
alias mygo="cd $MY_WS_GO"
alias myopt="cd $MY_WS_OPT"
alias mygocur="export GOPATH=`pwd`:$GOPATH"

alias setmyproxy="export HTTP_PROXY=\"http://127.0.0.1:1082\" HTTPS_PROXY=\"http://127.0.0.1:1082\""
alias unsetmyproxy="export HTTP_PROXY=\"\" && export HTTPS_PROXY=\"\""

alias mpw="cd $MY_WS_PWORK"
alias mpr="cd $MY_WS_PREPO"
